trigger:
  - main
pool:
  vmImage: ubuntu-latest

variables:
  solution: "./pasta/*.sln"
  buildPlataform: "Any CPU"
  buildConfiguration: "Release"

steps:

  - task: UseDotNet@2
    displayName: 'Install .Net SDK'
    inputs:
      packageType: 'sdk'
      version: '8.x'

  - script: dotnet restore $(solution)
    displayName: 'Restore Solution'

  - script: dotnet build $(solution) --configuration $(buildConfiguration)
    displayName: 'Build Solution'

  - script: dotnet test $(solution) --configuration $(buildConfiguration) --no-build --collect:"XPlat code Coverage"
    displayName: 'Test Solution'

  - task: Docker@2
    inputs:
      containerRegistry: "acriapidemohsouza"
      repository: "api-dio-demo"
      command: "buildAndPush"
      Dockerfile: "./pasta/Dockerfile"